# Generated by Django 5.2.17 on 2026-08-19 22:41

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoLocal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, help_text='Precio por unidad de medida del producto.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='precio')),
                ('stock_minimo', models.DecimalField(decimal_places=3, default=Decimal('0'), help_text='Se compara contra la suma de todos los lotes activos.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='stock mínimo')),
                ('dias_alerta_vencimiento', models.PositiveIntegerField(blank=True, help_text='Si queda vacío, se usa el configurado en el local.', null=True, verbose_name='días de alerta de vencimiento')),
                ('activo', models.BooleanField(default=True, help_text='Apagarlo deja de mostrar el producto sin borrar su historia.', verbose_name='activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='empresas.local', verbose_name='local')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='en_locales', to='productos.producto', verbose_name='producto')),
            ],
            options={
                'verbose_name': 'producto del local',
                'verbose_name_plural': 'productos del local',
                'ordering': ['producto__nombre'],
            },
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=50, verbose_name='número de lote')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='fecha de vencimiento')),
                ('cantidad', models.DecimalField(decimal_places=3, default=Decimal('0'), help_text='Siempre con decimales. La interfaz decide si los muestra.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='cantidad')),
                ('precio_oferta', models.DecimalField(blank=True, decimal_places=2, help_text='Para liquidar lo que está por vencer. Si es null, usa el precio normal.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='precio de oferta')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('producto_local', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lotes', to='stock.productolocal', verbose_name='producto del local')),
            ],
            options={
                'verbose_name': 'lote',
                'verbose_name_plural': 'lotes',
                'ordering': [models.OrderBy(models.F('fecha_vencimiento'), nulls_last=True), 'creado_en'],
            },
        ),
        migrations.AddIndex(
            model_name='productolocal',
            index=models.Index(fields=['local', 'activo'], name='prodlocal_local_activo_idx'),
        ),
        migrations.AddConstraint(
            model_name='productolocal',
            constraint=models.UniqueConstraint(fields=('producto', 'local'), name='un_producto_una_vez_por_local'),
        ),
        migrations.AddIndex(
            model_name='lote',
            index=models.Index(fields=['producto_local', 'fecha_vencimiento'], name='lote_prodlocal_venc_idx'),
        ),
        migrations.AddIndex(
            model_name='lote',
            index=models.Index(condition=models.Q(('activo', True), ('cantidad__gt', 0)), fields=['fecha_vencimiento'], name='lote_venc_activos_idx'),
        ),
    ]
