# Generated by Django 5.2.17 on 2026-08-19 22:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='descripción')),
                ('unidad_medida', models.CharField(choices=[('unidad', 'Unidad'), ('kg', 'Kilogramo'), ('g', 'Gramo'), ('l', 'Litro'), ('ml', 'Mililitro'), ('m', 'Metro')], default='unidad', max_length=10, verbose_name='unidad de medida')),
                ('controla_vencimiento', models.BooleanField(default=False, help_text='¿Este producto vence? Es una característica del producto, no del rubro.', verbose_name='controla vencimiento')),
                ('controla_lote', models.BooleanField(default=False, help_text='¿Se numera cada tanda recibida? El jamón tiene fecha pero puede no tener lote.', verbose_name='controla lote')),
                ('factor_conversion', models.DecimalField(blank=True, decimal_places=3, help_text='Cuántas unidades de este producto salen de una del padre. Ej: 30.', max_digits=12, null=True, verbose_name='factor de conversión')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='empresas.empresa', verbose_name='empresa')),
                ('producto_padre', models.ForeignKey(blank=True, help_text='Producto del que este sale al fraccionar. Ej: la caja de 30.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fracciones', to='productos.producto', verbose_name='producto padre')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CodigoBarra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, verbose_name='código')),
                ('principal', models.BooleanField(default=False, help_text='El que se muestra en la ficha. Solo uno por producto.', verbose_name='principal')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='codigos_barra', to='empresas.empresa', verbose_name='empresa')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigos', to='productos.producto', verbose_name='producto')),
            ],
            options={
                'verbose_name': 'código de barra',
                'verbose_name_plural': 'códigos de barra',
                'ordering': ['-principal', 'codigo'],
            },
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['empresa', 'nombre'], name='prod_empresa_nombre_idx'),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('factor_conversion__isnull', True), ('producto_padre__isnull', True)), models.Q(('factor_conversion__isnull', False), ('producto_padre__isnull', False)), _connector='OR'), name='producto_padre_y_factor_juntos'),
        ),
        migrations.AddConstraint(
            model_name='codigobarra',
            constraint=models.UniqueConstraint(fields=('empresa', 'codigo'), name='codigo_unico_por_empresa'),
        ),
        migrations.AddConstraint(
            model_name='codigobarra',
            constraint=models.UniqueConstraint(condition=models.Q(('principal', True)), fields=('producto',), name='un_solo_codigo_principal_por_producto'),
        ),
    ]
