# Generated by Django 5.2.17 on 2026-08-19 22:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='nombre de fantasía')),
                ('rut', models.CharField(max_length=20, unique=True, verbose_name='RUT')),
                ('razon_social', models.CharField(max_length=255, verbose_name='razón social')),
                ('giro', models.CharField(blank=True, max_length=255, verbose_name='giro')),
                ('activo', models.BooleanField(default=True, verbose_name='activa')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creada en')),
            ],
            options={
                'verbose_name': 'empresa',
                'verbose_name_plural': 'empresas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='nombre')),
                ('direccion', models.CharField(blank=True, max_length=255, verbose_name='dirección')),
                ('slug', models.SlugField(max_length=60, unique=True, verbose_name='identificador en la URL')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('maneja_vencimiento', models.BooleanField(default=True, help_text='Si está apagado, las fechas de vencimiento no se piden ni se muestran.', verbose_name='maneja vencimientos')),
                ('maneja_lotes', models.BooleanField(default=False, help_text='Requiere que maneje vencimientos. Permite numerar cada tanda recibida.', verbose_name='maneja lotes')),
                ('venta_por_medida', models.BooleanField(default=False, help_text="Habilita unidades distintas de 'unidad' (kg, litro, metro) y decimales en pantalla.", verbose_name='venta por medida')),
                ('permite_traspasos', models.BooleanField(default=False, verbose_name='permite traspasos entre locales')),
                ('consulta_stock_otros_locales', models.BooleanField(default=False, verbose_name='puede consultar stock de otros locales')),
                ('dias_alerta_vencimiento', models.PositiveIntegerField(default=30, help_text='Con cuántos días de anticipación avisar. En días, no en meses.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='días de alerta de vencimiento')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locales', to='empresas.empresa', verbose_name='empresa')),
            ],
            options={
                'verbose_name': 'local',
                'verbose_name_plural': 'locales',
                'ordering': ['empresa__nombre', 'nombre'],
                'constraints': [models.UniqueConstraint(fields=('empresa', 'nombre'), name='local_nombre_unico_por_empresa'), models.CheckConstraint(condition=models.Q(('maneja_lotes', False), ('maneja_vencimiento', True), _connector='OR'), name='local_lotes_requiere_vencimiento')],
            },
        ),
    ]
